version: '3'

services:

  authDb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authDb
    ports:
      - "3336:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - authNet
    volumes:
      - authVolume:/var/lib/mysql

  authDbMigration:
    image: authdbmigration
    environment:
      - DATABASE_URL=authDb
      - MYSQL_DATABASE=authDb
    depends_on:
      authDb:
        condition: service_healthy
    networks:
      - authNet

  auth:
    image: auth
    environment:
      - DATABASE_URL=authDb
      - MYSQL_DATABASE=authDb
    depends_on:
      - authDbMigration
    ports:
      - "5000:5000"
    networks:
      - authNet

  storeDb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3337:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - storeNet
    volumes:
      - storeVolume:/var/lib/mysql

  storeDbMigration:
    image: storedbmigration
    environment:
      - DATABASE_URL=storeDb
    depends_on:
      storeDb:
        condition: service_healthy
    networks:
      - storeNet

  customer:
    image: customer
    environment:
      - DATABASE_URL=storeDb
    depends_on:
      - storeDbMigration
    ports:
      - "5002:5002"
    networks:
      - storeNet

  courier:
    image: courier
    environment:
      - DATABASE_URL=storeDb
    depends_on:
      - storeDbMigration
    ports:
      - "5003:5003"
    networks:
      - storeNet

  owner:
    image: owner
    environment:
      - DATABASE_URL=storeDb
    depends_on:
      - storeDbMigration
    ports:
      - "5001:5001"
    networks:
      - storeNet

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - storeNet

networks:
  authNet:
  storeNet:

volumes:
  authVolume:
  storeVolume: