version: '3'

services:

  storeDb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  authDb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"