version: '3'

services:

  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data_authenticationDB:/var/lib/mysql
    networks:
      - authenticationNetwork

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    networks:
      - authenticationNetwork

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    ports:
      - "5001:5001"
    networks:
      - authenticationNetwork


  storeDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data_storeDB:/var/lib/mysql
    networks:
      - storeNetwork

  storeDBMigration:
    image: storedbmigration
    environment:
      - DATABASE_URL=storeDB
    networks:
      - storeNetwork

  daemon:
    image: daemon_image
    environment:
      - DATABASE_URL=storeDB
    networks:
      - storeNetwork
      - redisNetwork

  worker:
    image: storeworker
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5002:5002
    networks:
      - redisNetwork


  customer:
    image: storecustomer
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5003:5003
    networks:
      - storeNetwork


  admin:
    image: storeadmin
    environment:
      - DATABASE_URL=storeDB
    ports:
      - "5004:5004"
    networks:
      - storeNetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redisNetwork

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - authenticationNetwork
      - storeNetwork



volumes:
  data_authenticationDB:
  data_storeDB:

networks:
  authenticationNetwork:
  storeNetwork: