"""Changes 3

Revision ID: 3461cbef36ef
Revises: c00ccb6fd731
Create Date: 2023-07-13 17:58:17.505844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3461cbef36ef'
down_revision = 'c00ccb6fd731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productorder', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productorder', 'quantity')
    # ### end Alembic commands ###
