"""Changes 2

Revision ID: c00ccb6fd731
Revises: c1b34e1a3387
Create Date: 2023-07-13 17:41:15.393846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c00ccb6fd731'
down_revision = 'c1b34e1a3387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('orders', 'priceTOTAL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('priceTOTAL', mysql.FLOAT(), nullable=False))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
