"""Changes

Revision ID: c1b34e1a3387
Revises: 12f6a829eb8c
Create Date: 2023-07-13 17:37:52.680835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1b34e1a3387'
down_revision = '12f6a829eb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productorder', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('productorder', 'priceATM')
    op.drop_column('productorder', 'requested')
    op.drop_column('productorder', 'received')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productorder', sa.Column('received', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('productorder', sa.Column('requested', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('productorder', sa.Column('priceATM', mysql.FLOAT(), nullable=False))
    op.drop_column('productorder', 'price')
    # ### end Alembic commands ###
